---
ID: "2e699875-0530-4db9-be37-246d3880950a"
Parent: "86cbbe39-1ac3-4719-9c31-bcf99117864e"
Template: "86cbbe39-1ac3-4719-9c31-bcf99117864e"
Path: /sitecore/templates/Feature/Weather/Location/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170304T153930Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "6df006e7-9d2d-4eb1-b817-e2cb790d8244"
      Hint: City
      Value: $name
